### ISSUE TITLE
Application Error when trying to use online yapf formatter

### ISSUE THREAD

**Issue by aaronlelevier** [jpadilla/yapf-online#1]
I got an application error when trying to run the formatter on the Heroku app and the linked one in the README.  Just letting you know. Not sure how used this repo is. Thanks

<img width="1440" alt="screen shot 2018-02-01 at 2 54 41 pm" src="https://user-images.githubusercontent.com/5514112/35707787-fcb42b78-075f-11e8-9d2a-ed240085af1a.png">

<img width="1440" alt="screen shot 2018-02-01 at 2 54 52 pm" src="https://user-images.githubusercontent.com/5514112/35707792-0110a822-0760-11e8-90aa-21ff40e71044.png">

**Comment by jpadilla** [comment]
Just deleted the heroku app which was replaced by https://yapf.now.sh. Just tried it out and didn't get an Internal Server Error. Could you share the code you were trying to format?

**Comment by aaronlelevier** [comment]
It's working now. Sorry. Not sure why it didn't work before.  

Here is the code that I was trying to format:
```python
def merge_lists(l1, l2, key):
  merged = {}
  for item in l1+l2:
    if item[key] in merged:
      merged[item[key]].update(item)
    else:
      merged[item[key]] = item
  return [val for (_, val) in merged.items()]
```

**Comment by jpadilla** [comment]
Cool, will keep an eye out. If it pops up again let me know, thanks!
